default['versions']['git'] = '1:1.7.9*'
default['versions']['subversion'] = '1.6.17*'
default['versions']['nginx'] = '1.1.19*'
default['versions']['php5'] = '5.3.10*'
default['versions']['php5-mysql'] = '5.3.10*'
default['versions']['php5-pgsql'] = '5.3.10*'
default['versions']['php5-curl'] = '5.3.10*'
default['versions']['php5-cli'] = '5.3.10*'
default['versions']['php5-fpm'] = '5.3.10*'
default['versions']['php-pear'] = '5.3.10*'
default['versions']['mysql-server'] = '5.5.32*'
default['versions']['postgresql'] = '9.1*'
default['versions']['curl'] = '7.22.0*'
default['versions']['imagemagick'] = '8:6.6.9.7*'
default['versions']['php5-imagick'] = '3.1.0*'

